"""Explicit compatibility exports for the original monolithic utility module."""

from .common import (
    RANDOM_SEED,
    QCLogger,
    ensure_dirs,
    savefig,
    safe_name,
    clean_id,
    load_csv,
    as_numeric,
    pformat,
    fmt_ci,
)

from .cohorts import (
    discover_feature_cols,
    find_center_col,
    find_first_existing,
    cohort_audit_row,
    build_allcancer_cohort,
    build_noncancer_ready_cohort,
    make_center_split,
    cancer_subtype_columns,
    merge_treatment_labels,
    reshape_cmr_long,
    cmr_feature_cols,
)

from .survival import (
    variance_filter,
    prepare_design_with_params,
    fit_cox_model,
    univariate_cox_rank,
    internal_cv_choose_k,
    train_locked_model,
    load_model_bundle,
    apply_model_bundle,
    derive_thresholds,
    apply_thresholds_from_dict,
)

from .evaluation import (
    bootstrap_cindex,
    km_hr,
    performance_row,
    horizon_performance,
    predict_10yr,
    lrt_interaction,
    risk_tertiles_from_pred,
    transition_tables,
    cmr_analysis_table,
    adjusted_linear_regressions,
)

from .clinical_models import (
    one_age_covars_htn_diabetes,
    encode_train_test,
    train_cox_matrix,
    train_clinical_and_stacked,
    one_age_covars,
)

from .plots import (
    plot_km_high_low,
    plot_km_tertiles,
    forest_plot,
    alluvial_static,
    subgroup_analysis,
    feature_rank_shift_bump,
)

__all__ = [
    'RANDOM_SEED',
    'QCLogger',
    'ensure_dirs',
    'savefig',
    'safe_name',
    'clean_id',
    'load_csv',
    'as_numeric',
    'pformat',
    'fmt_ci',
    'discover_feature_cols',
    'find_center_col',
    'find_first_existing',
    'cohort_audit_row',
    'build_allcancer_cohort',
    'build_noncancer_ready_cohort',
    'make_center_split',
    'cancer_subtype_columns',
    'merge_treatment_labels',
    'reshape_cmr_long',
    'cmr_feature_cols',
    'variance_filter',
    'prepare_design_with_params',
    'fit_cox_model',
    'univariate_cox_rank',
    'internal_cv_choose_k',
    'train_locked_model',
    'load_model_bundle',
    'apply_model_bundle',
    'derive_thresholds',
    'apply_thresholds_from_dict',
    'bootstrap_cindex',
    'km_hr',
    'performance_row',
    'horizon_performance',
    'predict_10yr',
    'lrt_interaction',
    'risk_tertiles_from_pred',
    'transition_tables',
    'cmr_analysis_table',
    'adjusted_linear_regressions',
    'one_age_covars_htn_diabetes',
    'encode_train_test',
    'train_cox_matrix',
    'train_clinical_and_stacked',
    'one_age_covars',
    'plot_km_high_low',
    'plot_km_tertiles',
    'forest_plot',
    'alluvial_static',
    'subgroup_analysis',
    'feature_rank_shift_bump',
]
